#!/usr/bin/env bash

# Default Redis port
redis_port=6379

# Check for options
while :; do
  case "${1:-}" in
    -h|--help)
      echo "Usage:"
      echo "  port-forward-redis"
      echo
      echo "Options:"
      echo "  No options are required. This script simply connects to the local Redis server on port 6379."
      exit
      ;;
    -?*)
      echo "Error: unknown option: $1" >&2
      exit 1
      ;;
    *)
      break
  esac
  shift
done

echo "Connecting to local Redis server on port $redis_port..."
# Check if the Redis server is running locally using redis-cli
until redis-cli -p $redis_port ping | grep -q "PONG"; do
  echo "Waiting for Redis server to be available on 127.0.01:$redis_port..."
  sleep 1
done

echo "Local Redis server is available on  127.0.0.1:$redis_port"
